"""Top 50 AI news and reference sites with RSS feeds."""

AI_FEEDS = [
    # === AI Lab Blogs ===
    {
        "name": "OpenAI Blog",
        "rss_url": "https://openai.com/news/rss.xml",
        "website_url": "https://openai.com/news",
        "category": "AI Labs",
        "logo": "🤖",
    },
    {
        "name": "Google DeepMind",
        "rss_url": "https://deepmind.google/discover/blog/rss.xml",
        "website_url": "https://deepmind.google/discover/blog",
        "category": "AI Labs",
        "logo": "🧠",
    },
    {
        "name": "Google AI Blog",
        "rss_url": "https://blog.google/technology/ai/rss/",
        "website_url": "https://blog.google/technology/ai/",
        "category": "AI Labs",
        "logo": "🔍",
    },
    {
        "name": "Meta AI",
        "rss_url": "https://ai.meta.com/blog/rss/",
        "website_url": "https://ai.meta.com/blog/",
        "category": "AI Labs",
        "logo": "🌐",
    },
    {
        "name": "Microsoft AI Blog",
        "rss_url": "https://blogs.microsoft.com/ai/feed/",
        "website_url": "https://blogs.microsoft.com/ai/",
        "category": "AI Labs",
        "logo": "🪟",
    },
    {
        "name": "NVIDIA AI Blog",
        "rss_url": "https://blogs.nvidia.com/feed/",
        "website_url": "https://blogs.nvidia.com/",
        "category": "AI Labs",
        "logo": "💚",
    },
    {
        "name": "Hugging Face Blog",
        "rss_url": "https://huggingface.co/blog/feed.xml",
        "website_url": "https://huggingface.co/blog",
        "category": "AI Labs",
        "logo": "🤗",
    },
    {
        "name": "Anthropic News",
        "rss_url": "https://www.anthropic.com/news/rss",
        "website_url": "https://www.anthropic.com/news",
        "category": "AI Labs",
        "logo": "⚡",
    },
    {
        "name": "Mistral AI News",
        "rss_url": "https://mistral.ai/news/rss",
        "website_url": "https://mistral.ai/news/",
        "category": "AI Labs",
        "logo": "🌊",
    },
    {
        "name": "Apple ML Research",
        "rss_url": "https://machinelearning.apple.com/rss.xml",
        "website_url": "https://machinelearning.apple.com",
        "category": "AI Labs",
        "logo": "🍎",
    },
    {
        "name": "AWS Machine Learning Blog",
        "rss_url": "https://aws.amazon.com/blogs/machine-learning/feed/",
        "website_url": "https://aws.amazon.com/blogs/machine-learning/",
        "category": "AI Labs",
        "logo": "☁️",
    },
    # === Research ===
    {
        "name": "ArXiv — AI",
        "rss_url": "https://export.arxiv.org/rss/cs.AI",
        "website_url": "https://arxiv.org/list/cs.AI/recent",
        "category": "Research",
        "logo": "📄",
    },
    {
        "name": "ArXiv — Machine Learning",
        "rss_url": "https://export.arxiv.org/rss/cs.LG",
        "website_url": "https://arxiv.org/list/cs.LG/recent",
        "category": "Research",
        "logo": "📊",
    },
    {
        "name": "ArXiv — Computer Vision",
        "rss_url": "https://export.arxiv.org/rss/cs.CV",
        "website_url": "https://arxiv.org/list/cs.CV/recent",
        "category": "Research",
        "logo": "👁️",
    },
    {
        "name": "Papers With Code",
        "rss_url": "https://paperswithcode.com/latest/rss",
        "website_url": "https://paperswithcode.com",
        "category": "Research",
        "logo": "📑",
    },
    {
        "name": "Berkeley AI Research",
        "rss_url": "https://bair.berkeley.edu/blog/feed.xml",
        "website_url": "https://bair.berkeley.edu/blog/",
        "category": "Research",
        "logo": "🐻",
    },
    {
        "name": "Distill.pub",
        "rss_url": "https://distill.pub/rss.xml",
        "website_url": "https://distill.pub",
        "category": "Research",
        "logo": "🔬",
    },
    {
        "name": "fast.ai",
        "rss_url": "https://www.fast.ai/index.xml",
        "website_url": "https://www.fast.ai",
        "category": "Research",
        "logo": "🏃",
    },
    {
        "name": "ArXiv — NLP",
        "rss_url": "https://export.arxiv.org/rss/cs.CL",
        "website_url": "https://arxiv.org/list/cs.CL/recent",
        "category": "Research",
        "logo": "💬",
    },
    # === News ===
    {
        "name": "The Verge — AI",
        "rss_url": "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
        "website_url": "https://www.theverge.com/ai-artificial-intelligence",
        "category": "News",
        "logo": "📰",
    },
    {
        "name": "VentureBeat AI",
        "rss_url": "https://venturebeat.com/ai/feed/",
        "website_url": "https://venturebeat.com/ai/",
        "category": "News",
        "logo": "💼",
    },
    {
        "name": "TechCrunch AI",
        "rss_url": "https://techcrunch.com/category/artificial-intelligence/feed/",
        "website_url": "https://techcrunch.com/category/artificial-intelligence/",
        "category": "News",
        "logo": "🚀",
    },
    {
        "name": "MIT Technology Review — AI",
        "rss_url": "https://www.technologyreview.com/topic/artificial-intelligence/feed/",
        "website_url": "https://www.technologyreview.com/topic/artificial-intelligence/",
        "category": "News",
        "logo": "🎓",
    },
    {
        "name": "Wired — AI",
        "rss_url": "https://www.wired.com/feed/tag/artificial-intelligence/latest/rss",
        "website_url": "https://www.wired.com/tag/artificial-intelligence/",
        "category": "News",
        "logo": "⚡",
    },
    {
        "name": "Ars Technica",
        "rss_url": "https://feeds.arstechnica.com/arstechnica/technology-lab",
        "website_url": "https://arstechnica.com/tag/ai/",
        "category": "News",
        "logo": "🔭",
    },
    {
        "name": "IEEE Spectrum — AI",
        "rss_url": "https://spectrum.ieee.org/feeds/topic/artificial-intelligence.rss",
        "website_url": "https://spectrum.ieee.org/artificial-intelligence",
        "category": "News",
        "logo": "⚙️",
    },
    {
        "name": "ZDNet — AI",
        "rss_url": "https://www.zdnet.com/topic/artificial-intelligence/rss.xml",
        "website_url": "https://www.zdnet.com/topic/artificial-intelligence/",
        "category": "News",
        "logo": "📡",
    },
    {
        "name": "AI Business",
        "rss_url": "https://aibusiness.com/rss.xml",
        "website_url": "https://aibusiness.com",
        "category": "News",
        "logo": "💹",
    },
    {
        "name": "Synced Review",
        "rss_url": "https://syncedreview.com/feed/",
        "website_url": "https://syncedreview.com",
        "category": "News",
        "logo": "🔄",
    },
    {
        "name": "InfoQ AI",
        "rss_url": "https://feed.infoq.com/ai-ml-data-eng/",
        "website_url": "https://www.infoq.com/ai-ml-data-eng/",
        "category": "News",
        "logo": "ℹ️",
    },
    # === Newsletters & Blogs ===
    {
        "name": "The Batch — DeepLearning.AI",
        "rss_url": "https://www.deeplearning.ai/the-batch/feed/",
        "website_url": "https://www.deeplearning.ai/the-batch/",
        "category": "Newsletters",
        "logo": "📬",
    },
    {
        "name": "Import AI",
        "rss_url": "https://jack-clark.net/feed/",
        "website_url": "https://jack-clark.net",
        "category": "Newsletters",
        "logo": "📥",
    },
    {
        "name": "Last Week in AI",
        "rss_url": "https://lastweekin.ai/feed",
        "website_url": "https://lastweekin.ai",
        "category": "Newsletters",
        "logo": "📅",
    },
    {
        "name": "AI Snake Oil",
        "rss_url": "https://www.aisnakeoil.com/feed",
        "website_url": "https://www.aisnakeoil.com",
        "category": "Newsletters",
        "logo": "🐍",
    },
    {
        "name": "Machine Learning Mastery",
        "rss_url": "https://machinelearningmastery.com/feed/",
        "website_url": "https://machinelearningmastery.com",
        "category": "Newsletters",
        "logo": "🎯",
    },
    {
        "name": "Towards Data Science",
        "rss_url": "https://towardsdatascience.com/feed",
        "website_url": "https://towardsdatascience.com",
        "category": "Newsletters",
        "logo": "📈",
    },
    {
        "name": "Towards AI",
        "rss_url": "https://towardsai.net/feed",
        "website_url": "https://towardsai.net",
        "category": "Newsletters",
        "logo": "🎪",
    },
    {
        "name": "Analytics Vidhya",
        "rss_url": "https://www.analyticsvidhya.com/feed/",
        "website_url": "https://www.analyticsvidhya.com",
        "category": "Newsletters",
        "logo": "📉",
    },
    {
        "name": "Ben's Bites",
        "rss_url": "https://www.bensbites.com/feed",
        "website_url": "https://www.bensbites.com",
        "category": "Newsletters",
        "logo": "🍔",
    },
    # === Safety & Alignment ===
    {
        "name": "AI Alignment Forum",
        "rss_url": "https://www.alignmentforum.org/feed.xml",
        "website_url": "https://www.alignmentforum.org",
        "category": "Safety",
        "logo": "🛡️",
    },
    {
        "name": "LessWrong",
        "rss_url": "https://www.lesswrong.com/feed.xml?view=curated-rss",
        "website_url": "https://www.lesswrong.com",
        "category": "Safety",
        "logo": "🧐",
    },
    {
        "name": "Future of Life Institute",
        "rss_url": "https://futureoflife.org/feed/",
        "website_url": "https://futureoflife.org",
        "category": "Safety",
        "logo": "🌍",
    },
    {
        "name": "AI Now Institute",
        "rss_url": "https://ainowinstitute.org/feed",
        "website_url": "https://ainowinstitute.org",
        "category": "Safety",
        "logo": "⚖️",
    },
    # === Tools & Developers ===
    {
        "name": "Weights & Biases",
        "rss_url": "https://wandb.ai/fully-connected/rss.xml",
        "website_url": "https://wandb.ai/fully-connected",
        "category": "Tools",
        "logo": "⚖️",
    },
    {
        "name": "AssemblyAI Blog",
        "rss_url": "https://www.assemblyai.com/blog/rss/",
        "website_url": "https://www.assemblyai.com/blog/",
        "category": "Tools",
        "logo": "🎙️",
    },
    {
        "name": "Replicate Blog",
        "rss_url": "https://replicate.com/blog/rss",
        "website_url": "https://replicate.com/blog",
        "category": "Tools",
        "logo": "♻️",
    },
    {
        "name": "Scale AI Blog",
        "rss_url": "https://scale.com/blog/feed",
        "website_url": "https://scale.com/blog",
        "category": "Tools",
        "logo": "⚖️",
    },
    {
        "name": "Lightning AI Blog",
        "rss_url": "https://lightning.ai/blog/rss/",
        "website_url": "https://lightning.ai/blog",
        "category": "Tools",
        "logo": "⚡",
    },
    # === Venture & Business ===
    {
        "name": "a16z AI",
        "rss_url": "https://a16z.com/tag/ai/feed/",
        "website_url": "https://a16z.com/tag/ai/",
        "category": "Business",
        "logo": "💰",
    },
    {
        "name": "Benedict Evans",
        "rss_url": "https://www.ben-evans.com/benedictevans/rss.xml",
        "website_url": "https://www.ben-evans.com",
        "category": "Business",
        "logo": "📊",
    },
    {
        "name": "The Gradient",
        "rss_url": "https://thegradient.pub/rss/",
        "website_url": "https://thegradient.pub",
        "category": "Research",
        "logo": "📐",
    },
    {
        "name": "TOPBOTS",
        "rss_url": "https://www.topbots.com/feed/",
        "website_url": "https://www.topbots.com",
        "category": "Business",
        "logo": "🤖",
    },
    {
        "name": "Unite AI",
        "rss_url": "https://www.unite.ai/feed/",
        "website_url": "https://www.unite.ai",
        "category": "News",
        "logo": "🔗",
    },
    {
        "name": "404 Media",
        "rss_url": "https://www.404media.co/rss/",
        "website_url": "https://www.404media.co",
        "category": "News",
        "logo": "📟",
    },
    {
        "name": "AI Trends",
        "rss_url": "https://aitrends.com/feed/",
        "website_url": "https://aitrends.com",
        "category": "News",
        "logo": "📈",
    },
    {
        "name": "KDNuggets",
        "rss_url": "https://www.kdnuggets.com/feed",
        "website_url": "https://www.kdnuggets.com",
        "category": "Tools",
        "logo": "💎",
    },
]

CATEGORIES = sorted(set(f["category"] for f in AI_FEEDS))
